name: newt
services:
  newt:
    cpu_shares: 90
    command: []
    container_name: newt
    deploy:
      resources:
        limits:
          memory: 7937M
    environment:
      - NEWT_ID=...
      - NEWT_SECRET=.....
      - PANGOLIN_ENDPOINT=https://google.com
    hostname: newt
    image: fosrl/newt:latest
    labels:
      icon: https://raw.githubusercontent.com/aronorriv/Docker-AppsCasa/refs/heads/main/Pangolin/Pangolin.png
    restart: unless-stopped
    ports: []
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/aronorriv/Docker-AppsCasa/refs/heads/main/Pangolin/Pangolin.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: newt
  title:
    custom: ""
    en_us: newt
