name: beszel-agent
services:
  beszel-agent:
    cpu_shares: 90
    command: []
    container_name: beszel-agent
    deploy:
      resources:
        limits:
          memory: 7937M
    environment:
      - KEY=...
      - PORT=45876
    hostname: beszel-agent
    image: henrygd/beszel-agent:0.9.1
    labels:
      icon: https://raw.githubusercontent.com/aronorriv/Docker-AppsCasa/refs/heads/main/Beszel/beszel%20Logo.png
    ports:
      - target: 45876
        published: "45876"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    devices: []
    cap_add: []
    networks:
      - beszel_network
    privileged: false
networks:
  beszel_network:
    name: beszel_combined_network
    driver: bridge
x-casaos:
  author: self
  category: self-hosted
  description:
    en_us: Beszel-Agent.
  hostname: 
  icon: https://raw.githubusercontent.com/aronorriv/Docker-AppsCasa/refs/heads/main/Beszel/beszel%20Logo.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: beszel-agent
  title:
    custom: Beszel Agent
    en_us: Beszel Agent
